name: Backend - Manual Production Build

on:
  workflow_dispatch:

jobs:
  prod-build:
    strategy:
      matrix:
        provider: [azure, aws, gcp]
    uses: cloudsteak/cm-workflows/.github/workflows/production-build-push.yml@1.3.0
    with:
      image_name: evolvia-verify-lab-${{ matrix.provider }}
